# **Trabajo Practico Numero 1**

**Antes que nada**:</br> $para$ $todos$ $los$ $ejercicios$ $seran$ $necesarias$ $las$ $librerias$ **numpy** $y$ **matplotlib**, </br>$por$ $lo$ $tanto$, $las$ $importamos$

In [8]:
import numpy as np
import matplotlib as plt
import scipy as sp

## Ejercicio 1

In [9]:
def descompLU(A):
    '''
    Parametro: matriz A perteneciente a R^n*n.
    Retorna: Las dos matrices de descomposicion LU = A
    '''

    #Guardamos el numero de filas de A en una variable n
    #Obs: n tambien es el numero de columnas, pues A es cuadrada
    n = A.shape[0] 

    #¿Tiene algun 0 en la diagonal?
    if not np.diag(A).all():
        print('Error: Hay por lo menos un cero en la diagonal')
        identidad = np.eye(n)
        return (identidad,A)

    #Caso base: n = 1:
    if n == 1:
        # A = 1 * A = L * U
        L_22 = 1
        U_22 = A[0,0]
        return (L_22, U_22)

    #Definimos las variables que vamos a usar para calcular L y U
    a_11 = A[0,0] # es un escalar, elemento de la primera fila y primera columna de A
    A_12 = A[0,1:] # vector fila con n - 1 elementos (1ra fila de A - a_11)
    A_21 = A[1:,0] # vector columna con n - 1 elementos (1ra col de A - a_11)
    A_22 = A[1:,1:] # matriz menor de A, resultado te quietarle la 1ra fila y columna

    #Con estas variables definidas es facil obtener u_11, U_12 y L_21
    #usando las escuaciones dadas en la consigna:
    u_11 = a_11.copy()
    U_12 = A_12.copy()
    L_21 = A_21 / u_11

    #Ahora hacemos el llamado recursivo sobre el producto L_22*U_22
    #Vamos obteniendo la descomposicion de A_22 - L_21*U_12
    #Hasta que llegamos al caso base donde la matriz es de 1*1
    L_22, U_22 = descompLU(A_22 - L_21@U_12)

    #Armo las matrices finales:
    L = np.eye(n,k=0) #matriz n*n con 1's en la diagonal
    L[1:, 0] = L_21 #le agrego el vector columna
    L[1:,1:] = L_22 #le agrego el bloque obtenido con los llamados recursivos

    U = np.zeros_like(L) #matriz n*n con todos 0´s, uso el shape de L para referencia
    U[0,0] = u_11 #agrego el primero elemento en la matriz
    U[0,1:] = U_12 #agrego el vector fila
    U[1:,1:] = U_22 #le agrego el bloque obtenido con los llamados recursivos
    
    return (L,U)

In [10]:
# Ejemplo de uso
A = np.array([[4, 3, 2, 1],
              [2, 9, 7, 5],
              [4, 7, 7, 8],
              [6, 9, 8, 9]])


L, U = descompLU(A)
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

print("\nMatriz L*U:\n", np.dot(L,U))

Matriz L:
[[1.  0.  0.  0. ]
 [0.5 1.  0.  0. ]
 [1.  0.5 1.  0. ]
 [1.5 1.  2.  1. ]]

Matriz U:
[[ 4.  3.  2.  1.]
 [ 0.  4.  2.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -1.]]

Matriz L*U:
 [[4.  3.  2.  1. ]
 [2.  5.5 3.  0.5]
 [4.  5.  4.  3. ]
 [6.  8.5 7.  4.5]]


## Ejercicio 3

In [11]:
def resolverLU(A, b):
    '''
    Parametros:
        *matriz A n*n
        *vector b de n elementos
    Retorna:
        *x vector solucion de la ecuación Ax = b
    '''

    #Obtenemos L y U haciendo uso del ejercicio 1
    L, U = descompLU(A)

    #Resuelvo la ecuacion Ly = b especificada en la consigna
    y = sp.linalg.solve_triangular(L, b)

    #Con (y) puedo obtener la solucion a la ecuación Ux = y
    x = sp.linalg.solve_triangular(U, y)

    return x


In [12]:
# Ejemplo de uso
A = np.array([[4, 3, 2, 1],
              [2, 9, 7, 5],
              [4, 7, 7, 8],
              [6, 9, 8, 9]])

b = np.array([4,4,7,8])

x = resolverLU(A, b)
print(x)

[ -0.625 -10.5    23.     -8.   ]
