# **Trabajo Practico Numero 1**

**Antes que nada**:</br> $para$ $los$ $ejercicios$ $seran$ $necesarias$ $las$ $librerias$ **numpy**, **scipy** $y$ **matplotlib**, </br>$por$ $lo$ $tanto$, $las$ $importamos$

In [1]:
import numpy as np
import matplotlib as plt
import scipy as sp

## Ejercicio 1

Dada una matriz A $\in\mathbb{R}^{n \times n}$, devuelve las dos matrices L y U de la descomposición A = LU.

In [2]:
def descompLU(A):
#Si hay algún 0 en la diagonal de A, imprime un mensaje de error y devuelve las matrices In y A. 
    for p in range (0,len(A)): 
        if A[p][p]==0: 
            I = np.eye(len(A)) 
            return ('error, In= ', I , 'A= ', A) 
    #Creamos 2 matrices de 0s L y U del mismo tamaño que A. 
    L=np.zeros((len(A),len(A[0]))) 
    U=np.zeros((len(A),len(A[0]))) 

    for i in range(0,len(A)): 
    #La diagional de L es toda de 1s. 
        L[i][i]=1 
        j=0 
        m=i 
    #Genera recursivamente los valores de L por debajo de la diagonal en la fila i. 
        while j < i: 
            L[i][j] = A[i][j]/U[j][j] 
            k=0 
            while k < j: 
                L[i][j]=L[i][j]-(L[i][k]*U[k][j]/U[j][j]) 
                k=k+1 
            j=j+1 
    #Genera recursivamente los valores de U que no son 0 en la fila i. 
        while m<len(A):
            U[i][m] = A[i][m] 
            n=0 
            while n < i: 
                U[i][m]=U[i][m]-L[i][n]*U[n][m] 
                n=n+1 
            m=m+1 
    return(L,U)

In [3]:
# Ejemplo de uso
A = np.array([[4, 3, 2, 1],
              [2, 9, 7, 5],
              [4, 7, 7, 8],
              [6, 9, 8, 9]])


L, U = descompLU(A)
print("Matriz L:")
print(L)
print("\nMatriz U:")
print(U)

print("\nMatriz L*U:\n", np.dot(L,U))

Matriz L:
[[1.         0.         0.         0.        ]
 [0.5        1.         0.         0.        ]
 [1.         0.53333333 1.         0.        ]
 [1.5        0.6        0.77777778 1.        ]]

Matriz U:
[[4.         3.         2.         1.        ]
 [0.         7.5        6.         4.5       ]
 [0.         0.         1.8        4.6       ]
 [0.         0.         0.         1.22222222]]

Matriz L*U:
 [[4. 3. 2. 1.]
 [2. 9. 7. 5.]
 [4. 7. 7. 8.]
 [6. 9. 8. 9.]]


## Ejercicio 3

In [4]:
def resolverLU(A, b):
    '''
    Parametros:
        *matriz A n*n
        *vector b de n elementos
    Retorna:
        *x vector solucion de la ecuación Ax = b
    '''

    #Obtenemos L y U haciendo uso del ejercicio 1
    L, U = descompLU(A)

    #Resuelvo la ecuacion Ly = b especificada en la consigna
    y = sp.linalg.solve_triangular(L, b)

    #Con (y) puedo obtener la solucion a la ecuación Ux = y
    x = sp.linalg.solve_triangular(U, y)

    return x


In [5]:
# Ejemplo de uso
A = np.array([[4, 3, 2, 1],
              [2, 9, 7, 5],
              [4, 7, 7, 8],
              [6, 9, 8, 9]])

b = np.array([4,4,7,8])

x = resolverLU(A, b)
print(x)

[  0.62525253   6.87676768 -12.83838384   6.54545455]


## Ejercicio 5

In [7]:
def inversa(A):
    L = descompLU(A)[0]
    U = descompLU(A)[1]
    #Matriz identidad del tamaño de A.
    I= np.eye(len(A))
    i=0
    #Creamos una matriz Ainversa de 0s del mismo tamaño que A.
    Ainversa = np.zeros((len(A),len(A[0])))
    #Cada fila de Ainversa es igual a Aei.
    while i < len(I):
        #Resolvemos Ly=ei
        y = sp.linalg.solve_triangular(L,I[i], lower=True)
        #Resolvemos Ux=y
        x = sp.linalg.solve_triangular(U,y, lower=False)
        Ainversa[i] = x
        i = i+1
    #Devuelve la trnaspuesta de Ainversa (para que Aei sea cada columna).
    return(np.transpose(Ainversa))
        


In [10]:
# Ejemplo de uso
A = np.array([[4, 3, 2, 1],
              [2, 9, 7, 5],
              [4, 7, 7, 8],
              [6, 9, 8, 9]])

B = inversa(A)
print(B)

[[ 0  0  0  0]
 [ 0  0  0  1]
 [ 0  0  0 -2]
 [ 0  0  0  0]]


In [11]:
print(np.linalg.inv(A))

[[ 0.28787879 -0.12121212  0.09090909 -0.04545455]
 [-0.48484848  0.15151515 -1.36363636  1.18181818]
 [ 0.90909091  0.09090909  2.18181818 -2.09090909]
 [-0.51515152 -0.15151515 -0.63636364  0.81818182]]


## Ejercicio 6

In [13]:
# Obtengo una matriz generada aleatoriamente
Al = np.random.rand(10,10)

# Obtengo la matriz inversa usando la funcion del Ej. 5
inv_Al = inversa(Al)

# Obtengo el producto entre ambas matrices obtenidas
producto = np.dot(inv_Al, Al)

# Calculo el error en norma Frobenius
diferencia = producto - np.eye(len(producto)) #Obtengo la matriz para calcularle la norma Frobenius

# Calculo el radicando: sumo los cuadrados de la diagonal de la matriz diferencia
radicando = 0
for i in range (len(diferencia)):
    radicando = radicando + diferencia[i,i]**2

# Finalmente obtengo la raiz del radicando, obteniendo así el error
error_frobenius = np.sqrt(radicando)

error_frobenius

17.804990740659985

## Ejercicio 7

In [25]:
def errorRelativo (A,x,b):
    e = np.linalg.norm(A@x-b, ord=2)/np.linalg.norm(b, ord=2)
    return(e)

In [27]:
def generar_random(n, matrix=True):
    '''
    n: Numero entero
    matrix: Booleano, en caso de ser True la funcion devuelve una matriz de n*n
            con numeros aleatorios pertenecientes a [-1,1).
            En caso de ser False, la funcion devuelve un vector de n elementos,
            todos pertenecientes a [-1,1). Valor por defecto = True
    '''

    if matrix:
        # Genero matriz aleatoria de 200*200
        A_positiva = np.random.rand(n,n)
        # Matriz de tamaño nxn de números aleatorios en [-1,0)
        A_negativa = np.random.rand(n,n) - np.ones((n,n))
        # Matriz de tamaño nxn de números aleatorios en [-1,1)
        return A_positiva + A_negativa
        
    else:
        # Genero vector aleatorio
        x_positivo = np.random.rand(n)
        x_negativo = np.random.rand(n) - np.ones(n)
        return x_positivo + x_negativo

In [28]:
def error_matriz_i(i):
    '''
    Parametro: i: Numero entero 
    Retorna: Tupla conteniendo el error relativo de la solucion al sistema Ax = b (generado aleatoriamente)
             , al resolverlo de dos maneras distintas.
             Siendo A una matriz cuadrada en reales con i filas, y b un vector en reales con i elementos
            
    '''
    ln_error_relativo_x1 = 0
    ln_error_relativo_x2 = 0

    for n in range(10):

        A = generar_random(i)

        x = generar_random(i, matrix=False)

        # Defino b
        b = np.dot(A,x)

        # Calculo la solucion al sistema Ax = b usando la funcion del Ejercicio 3
        x1 = resolverLU(A,b)
        # Obtengo el error relativo
        ln_error_relativo_x1 = ln_error_relativo_x1 + errorRelativo(A,x1,b)

        # Calculo x2 = inv(A)b
        x2 = np.dot(inversa(A),b)
        # Obtengo el error relativo
        ln_error_relativo_x2 = ln_error_relativo_x2 + errorRelativo(A,x2,b)

    # Devuelvo una tupla conteniendo ambos errores relativos
    return (ln_error_relativo_x1,ln_error_relativo_x2)


In [23]:
def obtener_vectores():
    # Inicializo dos listas vacias para luego llenarlas con los elementos de los vectores finaless
    vector1, vector2 = [], []

    for i in range(10,201):
        # Obtengo la suma de los logaritmos de los errores relativos
        sumar1, sumar2 = error_matriz_i(i) 

        # Agrego los errores relativos en las listas correspondientes
        vector1.append(sumar1) 
        vector2.append(sumar2)

    # Creo los vectores con los elementos de las listas
    v1 = np.array(vector1)
    v2 = np.array(vector2)

    return (v1,v2)
